name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'

    - name: Configure kubectl
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 --decode > ~/.kube/config

    - name: Deploy Helm chart
      run: |
        helm upgrade --install kana-helm-demo ./kana-helm-demo --values ./kana-helm-demo/values.yaml
