apiVersion: v1
kind: Service
metadata:
  name: python-service1
spec:
  type: {{ .Values.pythonService1.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: python-service1
