apiVersion: v1
kind: Service
metadata:
  name: python-service2
spec:
  type: {{ .Values.pythonService2.service.type }}
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: python-service2
